# Generated by Django 3.2.22 on 2023-10-13 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Recipehub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipe',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
