# Generated by Django 3.2.21 on 2023-10-13 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Recipehub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('step_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='recipeequipment',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='recipeequipment',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('cup', 'Cup'), ('oz', 'Ounce'), ('lb', 'Pound'), ('fl oz', 'Fluid Ounce'), ('pint', 'Pint'), ('quart', 'Quart'), ('gallon', 'Gallon')], default='oz', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='equipment',
        ),
        migrations.DeleteModel(
            name='RecipeEquipment',
        ),
        migrations.AddField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recipehub.recipe'),
        ),
    ]
