# Generated by Django 3.2.21 on 2023-10-15 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipehub', '0002_auto_20231013_0300'),
        ('Recipehub', '0002_auto_20231013_0446'),
    ]

    operations = [
    ]
