# Generated by Django 3.2.21 on 2023-10-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipehub', '0003_merge_0002_auto_20231013_0300_0002_auto_20231013_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='No instructions provided.'),
        ),
    ]
